In [1]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model
import numpy as np

In [2]:
# ค่าเริ่มต้น
feature = [[5], [10]]

# ค่าเป้าหมาย
label = [10], [20]

In [3]:
poly = PolynomialFeatures(degree=3)

feature_ = poly.fit_transform(feature)
print(feature_)

[[   1.    5.   25.  125.]
 [   1.   10.  100. 1000.]]


In [4]:
feature_ = np.delete(feature_,(0),axis=1)
print(feature_)

[[   5.   25.  125.]
 [  10.  100. 1000.]]


In [5]:
clf = linear_model.LinearRegression()
clf.fit(feature_, label)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [7]:
# ค่าที่ต้องการทำนาย
predict= [5], [10]

predict_ = poly.fit_transform(predict)

predict_ = np.delete(predict_,(0),axis=1)
print(predict_)

[[   5.   25.  125.]
 [  10.  100. 1000.]]


In [10]:
print("Prediction = ")
print(clf.predict(predict_))

Prediction = 
[[10.]
 [20.]]
